from sqlalchemy.orm import Session
from app import crud, schemas, models
from app.core.config import settings
from app.db import base  # noqa: F401

# make sure all SQL Alchemy models are imported (app.db.base) before initializing DB
# otherwise, SQL Alchemy might fail to initialize relationships properly
# for more details: https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/28


def init_db(db: Session) -> None:
    # Tables should be created with Alembic migrations
    # But if you don't want to use migrations, create
    # the tables un-commenting the next line
    # Base.metadata.create_all(bind=engine)

    admin = crud.admin.get_by_username(db, username=settings.ADMIN_USERNAME)
    if not admin:
        admin_in = schemas.AdminCreate(
            username=settings.ADMIN_USERNAME,
            password=settings.ADMIN_PASSWORD,
            first_name='admin',
            last_name='admin'
        )
        admin = crud.admin.create(db, obj_in=admin_in)  # noqa: F841

    ######### Cargar data inicial ###########

    # Diagnósticos presuntivos

    db.add(models.Diagnosis(name="Acidez de estómago"))
    db.add(models.Diagnosis(name="Acné"))
    db.add(models.Diagnosis(name="Acúfenos"))
    db.add(models.Diagnosis(name="Adenoma hipofisiario"))
    db.add(models.Diagnosis(name="Aerofagia"))
    db.add(models.Diagnosis(name="Aftas bucales"))
    db.add(models.Diagnosis(name="Agorafobia"))
    db.add(models.Diagnosis(name="Alergia"))
    db.add(models.Diagnosis(name="Alergia al látex"))
    db.add(models.Diagnosis(name="Alergia al polen"))
    db.add(models.Diagnosis(name="Alergias alimentarias"))
    db.add(models.Diagnosis(name="Alopecia"))
    db.add(models.Diagnosis(name="Alzheimer"))
    db.add(models.Diagnosis(name="Amenorrea"))
    db.add(models.Diagnosis(name="Amigdalitis"))
    db.add(models.Diagnosis(name="Anemia"))
    db.add(models.Diagnosis(name="Aneurisma de aorta"))
    db.add(models.Diagnosis(name="Angina de pecho"))
    db.add(models.Diagnosis(name="Anisakiasis"))
    db.add(models.Diagnosis(name="Anorexia"))
    db.add(models.Diagnosis(name="Ansiedad"))
    db.add(models.Diagnosis(name="Apendicitis"))
    db.add(models.Diagnosis(name="Apnea del sueño"))
    db.add(models.Diagnosis(name="Arritmias"))
    db.add(models.Diagnosis(name="Arterioesclerosis"))
    db.add(models.Diagnosis(name="Artritis reumatoide"))
    db.add(models.Diagnosis(name="Artrosis"))
    db.add(models.Diagnosis(name="Asbestosis"))
    db.add(models.Diagnosis(name="Asma"))
    db.add(models.Diagnosis(name="Astigmatismo"))
    db.add(models.Diagnosis(name="Ataxia"))
    db.add(models.Diagnosis(name="Ateroesclerosis"))
    db.add(models.Diagnosis(name="Autismo"))
    db.add(models.Diagnosis(name="Balanitis"))
    db.add(models.Diagnosis(name="Bartolinitis"))
    db.add(models.Diagnosis(name="Botulismo"))
    db.add(models.Diagnosis(name="Bradicardia"))
    db.add(models.Diagnosis(name="Bronquiectasias"))
    db.add(models.Diagnosis(name="Bronquitis"))
    db.add(models.Diagnosis(name="Brucelosis"))
    db.add(models.Diagnosis(name="Bruxismo"))
    db.add(models.Diagnosis(name="Bulimia"))
    db.add(models.Diagnosis(name="Bullying"))
    db.add(models.Diagnosis(name="Bursitis"))
    db.add(models.Diagnosis(name="Callos"))
    db.add(models.Diagnosis(name="Cáncer de cabeza y cuello"))
    db.add(models.Diagnosis(name="Cáncer de colon"))
    db.add(models.Diagnosis(name="Cáncer de cuello de útero"))
    db.add(models.Diagnosis(name="Cáncer de endometrio"))
    db.add(models.Diagnosis(name="Cáncer de estómago"))
    db.add(models.Diagnosis(name="Cáncer de faringe"))
    db.add(models.Diagnosis(name="Cáncer de intestino delgado"))
    db.add(models.Diagnosis(name="Cáncer de laringe"))
    db.add(models.Diagnosis(name="Cáncer de las vías biliares"))
    db.add(models.Diagnosis(name="Cáncer de mama"))
    db.add(models.Diagnosis(name="Cáncer de ovario"))
    db.add(models.Diagnosis(name="Cáncer de páncreas"))
    db.add(models.Diagnosis(name="Cáncer de piel"))
    db.add(models.Diagnosis(name="Cáncer de próstata"))
    db.add(models.Diagnosis(name="Cáncer de pulmón"))
    db.add(models.Diagnosis(name="Cáncer de riñón"))
    db.add(models.Diagnosis(name="Cáncer de testículo"))
    db.add(models.Diagnosis(name="Cáncer de tiroides"))
    db.add(models.Diagnosis(name="Cáncer de uretra"))
    db.add(models.Diagnosis(name="Cáncer de vejiga"))
    db.add(models.Diagnosis(name="Candidiasis"))
    db.add(models.Diagnosis(name="Cardiopatías congénitas"))
    db.add(models.Diagnosis(name="Cataratas"))
    db.add(models.Diagnosis(name="Celiaquía"))
    db.add(models.Diagnosis(name="Cervicitis"))
    db.add(models.Diagnosis(name="Chikungunya"))
    db.add(models.Diagnosis(name="Ciática"))
    db.add(models.Diagnosis(name="Cirrosis"))
    db.add(models.Diagnosis(name="Citomegalovirus"))
    db.add(models.Diagnosis(name="Colecistitis"))
    db.add(models.Diagnosis(name="Colelitiasis"))
    db.add(models.Diagnosis(name="Cólera"))
    db.add(models.Diagnosis(name="Cólico del lactante"))
    db.add(models.Diagnosis(name="Cólico nefrótico"))
    db.add(models.Diagnosis(name="Colitis ulcerosa"))
    db.add(models.Diagnosis(name="Colon irritable"))
    db.add(models.Diagnosis(name="Conjuntivitis"))
    db.add(models.Diagnosis(name="Coronavirus"))
    db.add(models.Diagnosis(name="Corte de digestión o hidrocución"))
    db.add(models.Diagnosis(name="Creutzfeldt jakob (Vacas locas)"))
    db.add(models.Diagnosis(name="Degeneración macular asociada a la edad (DMAE)"))
    db.add(models.Diagnosis(name="Demencia"))
    db.add(models.Diagnosis(name="Demencia con cuerpos de Lewy"))
    db.add(models.Diagnosis(name="Dengue"))
    db.add(models.Diagnosis(name="Depresión"))
    db.add(models.Diagnosis(name="Dermatitis atípica"))
    db.add(models.Diagnosis(name="Dermatitis del pañal"))
    db.add(models.Diagnosis(name="Dermatitis seborreica"))
    db.add(models.Diagnosis(name="Derrame pleural"))
    db.add(models.Diagnosis(name="Desprendimiento de retina"))
    db.add(models.Diagnosis(name="Diabetes"))
    db.add(models.Diagnosis(name="Diarrea"))
    db.add(models.Diagnosis(name="Diarrea del viajero"))
    db.add(models.Diagnosis(name="Difteria"))
    db.add(models.Diagnosis(name="Disfunción sexual femenina"))
    db.add(models.Diagnosis(name="Dislexia"))
    db.add(models.Diagnosis(name="Dismenorrea"))
    db.add(models.Diagnosis(name="Dismorfofobia"))
    db.add(models.Diagnosis(name="Dispepsia"))
    db.add(models.Diagnosis(name="Diverticulitis"))
    db.add(models.Diagnosis(name="Dolor de cabeza o cefalea"))
    db.add(models.Diagnosis(name="Eccema"))
    db.add(models.Diagnosis(name="Edema Pulmonar"))
    db.add(models.Diagnosis(name="ELA (esclerosis lateral amiotrófica)"))
    db.add(models.Diagnosis(name="Embolia pulmonar"))
    db.add(models.Diagnosis(name="Encefalitis"))
    db.add(models.Diagnosis(name="Encefalopatía hepática"))
    db.add(models.Diagnosis(name="Endocarditis"))
    db.add(models.Diagnosis(name="Endometriosis"))
    db.add(models.Diagnosis(name="Enfermedad de Crohn"))
    db.add(models.Diagnosis(name="Enfermedad de Kawasaki"))
    db.add(models.Diagnosis(name="Enfermedad de Paget"))
    db.add(models.Diagnosis(name="Enfermedad de Whipple"))
    db.add(models.Diagnosis(name="Enfermedad de Wilson"))
    db.add(models.Diagnosis(name="Enfermedad del sueño"))
    db.add(models.Diagnosis(name="Enfermedad por virus de Marburgo"))
    db.add(models.Diagnosis(name="Enfermedad renal crónica"))
    db.add(models.Diagnosis(name="Enfermedad tromboembólica venosa"))
    db.add(models.Diagnosis(name="Enfisema"))
    db.add(models.Diagnosis(name="Enuresis"))
    db.add(models.Diagnosis(name="Epilepsia"))
    db.add(models.Diagnosis(name="EPOC (enfermedad pulmonar obstructiva crónica)"))
    db.add(models.Diagnosis(name="Escarlatina"))
    db.add(models.Diagnosis(name="Esclerodermia"))
    db.add(models.Diagnosis(name="Esclerosis múltiple"))
    db.add(models.Diagnosis(name="Escoliosis"))
    db.add(models.Diagnosis(name="Esofagitis"))
    db.add(models.Diagnosis(name="Esofagitis eosinofólica"))
    db.add(models.Diagnosis(name="Esófago de Barret"))
    db.add(models.Diagnosis(name="Espina bífida"))
    db.add(models.Diagnosis(name="Espolón calcáneo"))
    db.add(models.Diagnosis(name="Espondilitis anquilosante"))
    db.add(models.Diagnosis(name="Esquizofrenia"))
    db.add(models.Diagnosis(name="Esterilidad e infertilidad"))
    db.add(models.Diagnosis(name="Estrabismo"))
    db.add(models.Diagnosis(name="Estreñimiento"))
    db.add(models.Diagnosis(name="Estrés"))
    db.add(models.Diagnosis(name="Factores de riesgo cardiovascular"))
    db.add(models.Diagnosis(name="Faringitis"))
    db.add(models.Diagnosis(name="Faringoamigdalitis"))
    db.add(models.Diagnosis(name="Fascitis plantar"))
    db.add(models.Diagnosis(name="Fenilcetonuria"))
    db.add(models.Diagnosis(name="Fibromialgia"))
    db.add(models.Diagnosis(name="Fibrosis pulmonar"))
    db.add(models.Diagnosis(name="Fibrosis pulmonar idiopática"))
    db.add(models.Diagnosis(name="Fibrosis Quística"))
    db.add(models.Diagnosis(name="Fiebre amarilla"))
    db.add(models.Diagnosis(name="Fiebre del heno"))
    db.add(models.Diagnosis(name="Fiebre tifoidea"))
    db.add(models.Diagnosis(name="Fiebres hemorrágicas"))
    db.add(models.Diagnosis(name="Fimosis"))
    db.add(models.Diagnosis(name="Fobia social"))
    db.add(models.Diagnosis(name="Gases y flatulencias"))
    db.add(models.Diagnosis(name="Gastritis"))
    db.add(models.Diagnosis(name="Gastroenteritis"))
    db.add(models.Diagnosis(name="Glaucoma"))
    db.add(models.Diagnosis(name="Golpe de calor"))
    db.add(models.Diagnosis(name="Gonorrea"))
    db.add(models.Diagnosis(name="Gota"))
    db.add(models.Diagnosis(name="Gripe"))
    db.add(models.Diagnosis(name="Hafefobia"))
    db.add(models.Diagnosis(name="Halitosis"))
    db.add(models.Diagnosis(name="Hematoma subdural"))
    db.add(models.Diagnosis(name="Hemocromatosis"))
    db.add(models.Diagnosis(name="Hemofilia"))
    db.add(models.Diagnosis(name="Hemorragias ginecológicas"))
    db.add(models.Diagnosis(name="Hemorroides"))
    db.add(models.Diagnosis(name="Hepatitis A"))
    db.add(models.Diagnosis(name="Hepatitis B"))
    db.add(models.Diagnosis(name="Hepatitis C"))
    db.add(models.Diagnosis(name="Hernia discal"))
    db.add(models.Diagnosis(name="Hernia inguinal"))
    db.add(models.Diagnosis(name="Herpes labial"))
    db.add(models.Diagnosis(name="Herpes zóster"))
    db.add(models.Diagnosis(name="Hidradenitis supurativa"))
    db.add(models.Diagnosis(name="Hidrocele"))
    db.add(models.Diagnosis(name="Hipercolesterolemia"))
    db.add(models.Diagnosis(name="Hipercolesterolemia familiar"))
    db.add(models.Diagnosis(name="Hiperhidrosis"))
    db.add(models.Diagnosis(name="Hipermenorrea"))
    db.add(models.Diagnosis(name="Hipermetropía"))
    db.add(models.Diagnosis(name="Hiperplasia benigna de próstata"))
    db.add(models.Diagnosis(name="Hipertensión arterial"))
    db.add(models.Diagnosis(name="Hipertiroidismo"))
    db.add(models.Diagnosis(name="Hipoglucemia"))
    db.add(models.Diagnosis(name="Hipotensión"))
    db.add(models.Diagnosis(name="Hipotiroidismo"))
    db.add(models.Diagnosis(name="Hirsutismo"))
    db.add(models.Diagnosis(name="Hongos"))
    db.add(models.Diagnosis(name="Ictus"))
    db.add(models.Diagnosis(name="Impétigo"))
    db.add(models.Diagnosis(name="Impotencia/ disfunción eréctil"))
    db.add(models.Diagnosis(name="Incontinencia urinaria"))
    db.add(models.Diagnosis(name="Infarto de miocardio"))
    db.add(models.Diagnosis(name="Infección urinaria o cistitis"))
    db.add(models.Diagnosis(name="Insomnio"))
    db.add(models.Diagnosis(name="Insuficiencia cardiaca"))
    db.add(models.Diagnosis(name="Intolerancia a la lactosa"))
    db.add(models.Diagnosis(name="Juanetes"))
    db.add(models.Diagnosis(name="Ladillas (piojos del pubis)"))
    db.add(models.Diagnosis(name="Legionella"))
    db.add(models.Diagnosis(name="Leishmaniasis"))
    db.add(models.Diagnosis(name="Lengua geográfica o glositis migratoria benigna"))
    db.add(models.Diagnosis(name="Lepra"))
    db.add(models.Diagnosis(name="Leucemia"))
    db.add(models.Diagnosis(name="Linfoma"))
    db.add(models.Diagnosis(name="Lipedema"))
    db.add(models.Diagnosis(name="Lipotimia"))
    db.add(models.Diagnosis(name="Listeriosis"))
    db.add(models.Diagnosis(name="Litiasis renal"))
    db.add(models.Diagnosis(name="Ludopatía"))
    db.add(models.Diagnosis(name="Lumbalgia"))
    db.add(models.Diagnosis(name="Lupus"))
    db.add(models.Diagnosis(name="Malaria"))
    db.add(models.Diagnosis(name="Melanoma"))
    db.add(models.Diagnosis(name="Melanoma metastásico"))
    db.add(models.Diagnosis(name="Melasma"))
    db.add(models.Diagnosis(name="Meningitis"))
    db.add(models.Diagnosis(name="Mielitis transversa"))
    db.add(models.Diagnosis(name="Mieloma múltiple"))
    db.add(models.Diagnosis(name="Migrañas"))
    db.add(models.Diagnosis(name="Miocardiopatía"))
    db.add(models.Diagnosis(name="Miomas uterinos"))
    db.add(models.Diagnosis(name="Miopía"))
    db.add(models.Diagnosis(name="Mobbing"))
    db.add(models.Diagnosis(name="Molusco contagioso"))
    db.add(models.Diagnosis(name="Mononucleosis"))
    db.add(models.Diagnosis(name="Muerte súbita cardiaca"))
    db.add(models.Diagnosis(name="Narcolepsia"))
    db.add(models.Diagnosis(name="Neumonía"))
    db.add(models.Diagnosis(name="Neumotórax"))
    db.add(models.Diagnosis(name="Obesidad"))
    db.add(models.Diagnosis(name="Ojo seco"))
    db.add(models.Diagnosis(name="Ojo vago"))
    db.add(models.Diagnosis(name="Orquitis"))
    db.add(models.Diagnosis(name="Ortorexia"))
    db.add(models.Diagnosis(name="Orzuelo"))
    db.add(models.Diagnosis(name="Osteoporosis"))
    db.add(models.Diagnosis(name="Osteosarcoma"))
    db.add(models.Diagnosis(name="Otitis"))
    db.add(models.Diagnosis(name="Pancreatitis"))
    db.add(models.Diagnosis(name="Paperas (parotiditis)"))
    db.add(models.Diagnosis(name="Parálisis de Bell"))
    db.add(models.Diagnosis(name="Parálisis del sueño"))
    db.add(models.Diagnosis(name="Parkinson"))
    db.add(models.Diagnosis(name="Pericarditis"))
    db.add(models.Diagnosis(name="Peste"))
    db.add(models.Diagnosis(name="Pie de atleta"))
    db.add(models.Diagnosis(name="Pielonefritis"))
    db.add(models.Diagnosis(name="Pies cavos"))
    db.add(models.Diagnosis(name="Pies planos"))
    db.add(models.Diagnosis(name="Pies zambos"))
    db.add(models.Diagnosis(name="Poliomielitis"))
    db.add(models.Diagnosis(name="Preeclampsia"))
    db.add(models.Diagnosis(name="Presbicia"))
    db.add(models.Diagnosis(name="Prostatitis"))
    db.add(models.Diagnosis(name="Psoriasis"))
    db.add(models.Diagnosis(name="Rabia"))
    db.add(models.Diagnosis(name="Rectocele"))
    db.add(models.Diagnosis(name="Retinoblastoma"))
    db.add(models.Diagnosis(name="Retinopatía diabética"))
    db.add(models.Diagnosis(name="Rinitis"))
    db.add(models.Diagnosis(name="Rosácea"))
    db.add(models.Diagnosis(name="Rotavirus"))
    db.add(models.Diagnosis(name="Rubéola"))
    db.add(models.Diagnosis(name="Salmonelosis"))
    db.add(models.Diagnosis(name="Sarampión"))
    db.add(models.Diagnosis(name="Sarcoidosis"))
    db.add(models.Diagnosis(name="Sarcoma"))
    db.add(models.Diagnosis(name="Sepsis"))
    db.add(models.Diagnosis(name="Sífilis"))
    db.add(models.Diagnosis(name="Silicosis"))
    db.add(models.Diagnosis(name="Síndrome de burnout"))
    db.add(models.Diagnosis(name="Síndrome de Diógenes"))
    db.add(models.Diagnosis(name="Síndrome de Down"))
    db.add(models.Diagnosis(name="Síndrome de Dravet"))
    db.add(models.Diagnosis(name="Síndrome de estrés postraumático"))
    db.add(models.Diagnosis(name="Síndrome de fatiga crónica"))
    db.add(models.Diagnosis(name="Síndrome de Ganser"))
    db.add(models.Diagnosis(name="Síndrome de Gilbert"))
    db.add(models.Diagnosis(name="Síndrome de Gorlin-Goltz"))
    db.add(models.Diagnosis(name="Síndrome de Guillain-Barré"))
    db.add(models.Diagnosis(name="Síndrome de hiperestimulación ovárica"))
    db.add(models.Diagnosis(name="Síndrome de Marfan"))
    db.add(models.Diagnosis(name="Síndrome de Patau"))
    db.add(models.Diagnosis(name="Síndrome de Reiter"))
    db.add(models.Diagnosis(name="Síndrome de Rett"))
    db.add(models.Diagnosis(name="Síndrome de Reye"))
    db.add(models.Diagnosis(name="Síndrome de Sanfilippo"))
    db.add(models.Diagnosis(name="Síndrome de Sjögren"))
    db.add(models.Diagnosis(name="Síndrome de Smith-Magenis"))
    db.add(models.Diagnosis(name="Síndrome de Tourette"))
    db.add(models.Diagnosis(name="Síndrome de Turner"))
    db.add(models.Diagnosis(name="Síndrome de Williams"))
    db.add(models.Diagnosis(name="Síndrome de Wolfram"))
    db.add(models.Diagnosis(name="Síndrome del túnel carpiano"))
    db.add(models.Diagnosis(name="Síndrome postvacacional"))
    db.add(models.Diagnosis(name="Síndromes mielodisplásicos (SMD)"))
    db.add(models.Diagnosis(name="Sinus Pilonidal"))
    db.add(models.Diagnosis(name="Sinusitis"))
    db.add(models.Diagnosis(name="Siringomielia"))
    db.add(models.Diagnosis(name="Sobrecrecimiento bacteriano o SIBO"))
    db.add(models.Diagnosis(name="Sonambulismo"))
    db.add(models.Diagnosis(name="Tendinitis"))
    db.add(models.Diagnosis(name="Tétanos"))
    db.add(models.Diagnosis(name="Tortícolis"))
    db.add(models.Diagnosis(name="Tos ferina"))
    db.add(models.Diagnosis(name="Toxoplasmosis"))
    db.add(models.Diagnosis(name="Trastorno bipolar"))
    db.add(models.Diagnosis(name="Trastorno de conducta del sueño en fase REM"))
    db.add(models.Diagnosis(name="Trastorno de menstruación"))
    db.add(models.Diagnosis(name="Trastorno obsesivo compulsivo (TOC)"))
    db.add(models.Diagnosis(name="Trastorno por atracón"))
    db.add(models.Diagnosis(
        name="Trastorno por déficit de atención e hiperactividad (TDAH)"))
    db.add(models.Diagnosis(name="Trastornos del ritmo circadiano"))
    db.add(models.Diagnosis(name="Tricomoniasis"))
    db.add(models.Diagnosis(name="Trombosis venosa (flebitis)"))
    db.add(models.Diagnosis(name="Tuberculosis"))
    db.add(models.Diagnosis(name="Tumores cerebrales"))
    db.add(models.Diagnosis(name="Uñas encarnadas (onicocriptosis)"))
    db.add(models.Diagnosis(name="Uretritis"))
    db.add(models.Diagnosis(name="Urticaria"))
    db.add(models.Diagnosis(name="Vaginitis o vulvovaginitis"))
    db.add(models.Diagnosis(name="Vaginosis bacteriana"))
    db.add(models.Diagnosis(name="Varicela"))
    db.add(models.Diagnosis(name="Varices"))
    db.add(models.Diagnosis(name="Varicocele"))
    db.add(models.Diagnosis(name="Vasculitis"))
    db.add(models.Diagnosis(name="Vegetaciones"))
    db.add(models.Diagnosis(name="Vértigo"))
    db.add(models.Diagnosis(name="Vigorexia"))
    db.add(models.Diagnosis(name="VIH / Sida"))
    db.add(models.Diagnosis(name="Virus del Nilo Occidental"))
    db.add(models.Diagnosis(name="Virus del papiloma humano (VPH)"))
    db.add(models.Diagnosis(name="Virus Zika"))
    db.add(models.Diagnosis(name="Vitíligo"))
    db.add(models.Diagnosis(name="Vulvitis"))

    # Tipos de estudio

    db.add(models.TypeStudy(
        name="Exoma",
        study_consent_template="<h3>Consentimiento informado</h3>"
        "<h5>Titulo del estudio</h5>"
        "<p>Estudio sobre el exoma...<p>"
        "<h5>Objetivo del estudio</h5>"
        "<p>En caracter de ... </p>"
        "<h5>Riesgos</h5>"
        "<p>Según a lo referido a las últimas investigaciones, se "
        "ha comprobado que...</p>"
        "<h2>AUTORIZACIÓN<h2>"
        "<p> En caracter de ... < /p >"))
    db.add(models.TypeStudy(
        name="Genoma mitoclondria completo",
        study_consent_template="<h3>Consentimiento informado</h3>"
        "<h5>Titulo del estudio</h5>"
        "<p>Estudio sobre Genoma mitoclondria completo...<p>"
        "<h5>Objetivo del estudio</h5>"
        "<p>En caracter de ... </p>"
        "<h5>Riesgos</h5>"
        "<p > En caracter de ... </p>"
        "<h2>AUTORIZACIÓN<h2>"
        "<p > En caracter de ... </p>"))
    db.add(models.TypeStudy(
        name="Carrier de enfermedades monogénicas recesivas", study_consent_template="wcwc"))
    db.add(models.TypeStudy(name="Cariotipo", study_consent_template="wcwvc"))
    db.add(models.TypeStudy(name="Array CGH", study_consent_template="wvewev"))

    db.commit()
