"""first commit

Revision ID: 042342db64c4
Revises: 
Create Date: 2021-10-30 08:31:20.743282

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from app.models import StudyState

# revision identifiers, used by Alembic.
revision = '042342db64c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthinsurance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('telephone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_healthinsurance_email'), 'healthinsurance', ['email'], unique=True)
    op.create_index(op.f('ix_healthinsurance_id'), 'healthinsurance', ['id'], unique=False)
    op.create_index(op.f('ix_healthinsurance_name'), 'healthinsurance', ['name'], unique=False)
    op.create_index(op.f('ix_healthinsurance_telephone'), 'healthinsurance', ['telephone'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('licence', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('dni', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('health_insurance_number', sa.Integer(), nullable=True),
    sa.Column('health_insurance_id', sa.Integer(), nullable=True),
    sa.Column('clinical_history', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['health_insurance_id'], ['healthinsurance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result', sa.Boolean(), nullable=True),
    sa.Column('date_report', sa.Date(), nullable=True),
    sa.Column('informant_doctor_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('state', sqlalchemy_utils.types.choice.ChoiceType(StudyState), nullable=True),
    sa.ForeignKeyConstraint(['informant_doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_id'), 'study', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_id'), table_name='study')
    op.drop_table('study')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_healthinsurance_telephone'), table_name='healthinsurance')
    op.drop_index(op.f('ix_healthinsurance_name'), table_name='healthinsurance')
    op.drop_index(op.f('ix_healthinsurance_id'), table_name='healthinsurance')
    op.drop_index(op.f('ix_healthinsurance_email'), table_name='healthinsurance')
    op.drop_table('healthinsurance')
    # ### end Alembic commands ###
