"""empty message

Revision ID: 04b3279fb7e3
Revises: b3c140004de1
Create Date: 2021-11-14 22:37:45.136641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b3279fb7e3'
down_revision = 'b3c140004de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study', 'current_state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study', 'current_state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
