"""Add column last_name to User model

Revision ID: 12fd05b3f483
Revises: 042342db64c4
Create Date: 2021-10-31 20:08:47.396513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12fd05b3f483'
down_revision = '042342db64c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referringphysician',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('licence', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_referringphysician_id'), 'referringphysician', ['id'], unique=False)
    op.create_index(op.f('ix_referringphysician_licence'), 'referringphysician', ['licence'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referringphysician_licence'), table_name='referringphysician')
    op.drop_index(op.f('ix_referringphysician_id'), table_name='referringphysician')
    op.drop_table('referringphysician')
    # ### end Alembic commands ###
