"""empty message

Revision ID: 267922b2ec8e
Revises: 331dee8a67d2
Create Date: 2021-11-07 01:35:50.349630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267922b2ec8e'
down_revision = '331dee8a67d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
