"""empty message

Revision ID: 2e911d95a8db
Revises: 4ddf9104348b
Create Date: 2021-10-31 21:26:14.576721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e911d95a8db'
down_revision = '4ddf9104348b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
