"""empty message

Revision ID: 331dee8a67d2
Revises: 74702f97e67c
Create Date: 2021-11-06 18:18:47.855796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331dee8a67d2'
down_revision = '74702f97e67c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.Column('retired_by', sa.String(), nullable=True),
    sa.Column('ml_extracted', sa.Float(), nullable=True),
    sa.Column('freezer_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_id'), 'sample', ['id'], unique=False)
    op.alter_column('study', 'current_state',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study', 'current_state',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_sample_id'), table_name='sample')
    op.drop_table('sample')
    # ### end Alembic commands ###
