"""empty message

Revision ID: 3d034368f7b2
Revises: 04b3279fb7e3
Create Date: 2021-11-15 12:32:37.891568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d034368f7b2'
down_revision = '04b3279fb7e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
