"""empty message

Revision ID: 4ddf9104348b
Revises: b08199a10c3b
Create Date: 2021-10-31 21:20:15.005831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ddf9104348b'
down_revision = 'b08199a10c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
