"""arreglada columna license

Revision ID: 7528816010db
Revises: 042342db64c4
Create Date: 2021-10-30 17:37:46.855510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7528816010db'
down_revision = '042342db64c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('license', sa.Integer(), nullable=True))
    op.drop_column('user', 'licence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('licence', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'license')
    # ### end Alembic commands ###
