"""empty message

Revision ID: 762978ead34c
Revises: 3d034368f7b2
Create Date: 2021-11-15 17:01:32.933615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762978ead34c'
down_revision = '3d034368f7b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
