"""empty message

Revision ID: 7778a81a106a
Revises: 6326a3f5d77e
Create Date: 2021-11-05 05:44:00.419457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7778a81a106a'
down_revision = '6326a3f5d77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    sa.UniqueConstraint('user_id', 'role_id', name='unique_user_role')
    )
    op.add_column('report', sa.Column('reporting_physician_id', sa.Integer(), nullable=True))
    op.drop_constraint('report_informant_physician_id_fkey', 'report', type_='foreignkey')
    op.create_foreign_key(None, 'report', 'user', ['reporting_physician_id'], ['id'])
    op.drop_column('report', 'informant_physician_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('informant_physician_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.create_foreign_key('report_informant_physician_id_fkey', 'report', 'user', ['informant_physician_id'], ['id'])
    op.drop_column('report', 'reporting_physician_id')
    op.drop_table('user_roles')
    # ### end Alembic commands ###
