"""empty message

Revision ID: 80076517aaf4
Revises: e87efa504ad6
Create Date: 2021-11-09 05:46:13.622522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80076517aaf4'
down_revision = 'e87efa504ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'date_appointment',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('samplebatch', sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('samplebatch', sa.Column('current_state', sa.String(), nullable=True))
    op.add_column('samplebatch', sa.Column('current_state_entered_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('study', sa.Column('signed_consent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'signed_consent')
    op.drop_column('samplebatch', 'current_state_entered_date')
    op.drop_column('samplebatch', 'current_state')
    op.drop_column('samplebatch', 'updated_date')
    op.alter_column('appointment', 'date_appointment',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
