"""modified_user_and_created_healthinsurance_and_study

Revision ID: 8010c7229f8f
Revises: 64e161ec0bda
Create Date: 2021-10-27 03:35:12.076917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8010c7229f8f'
down_revision = '64e161ec0bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthinsurance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_healthinsurance_email'), 'healthinsurance', ['email'], unique=True)
    op.create_index(op.f('ix_healthinsurance_id'), 'healthinsurance', ['id'], unique=False)
    op.create_index(op.f('ix_healthinsurance_name'), 'healthinsurance', ['name'], unique=False)
    op.create_index(op.f('ix_healthinsurance_telephone'), 'healthinsurance', ['telephone'], unique=False)
    op.create_table('study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result', sa.Boolean(), nullable=True),
    sa.Column('date_report', sa.Date(), nullable=True),
    sa.Column('informant_doctor_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['informant_doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_id'), 'study', ['id'], unique=False)
    op.add_column('user', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('type', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('licence', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('dni', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('birth_date', sa.Date(), nullable=False))
    op.add_column('user', sa.Column('health_insurance_number', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('health_insurance_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('clinical_history', sa.Text(), nullable=True))
    op.drop_index('ix_user_full_name', table_name='user')
    op.create_foreign_key(None, 'user', 'healthinsurance', ['health_insurance_id'], ['id'])
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_index('ix_user_full_name', 'user', ['full_name'], unique=False)
    op.drop_column('user', 'clinical_history')
    op.drop_column('user', 'health_insurance_id')
    op.drop_column('user', 'health_insurance_number')
    op.drop_column('user', 'birth_date')
    op.drop_column('user', 'dni')
    op.drop_column('user', 'licence')
    op.drop_column('user', 'type')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_index(op.f('ix_study_id'), table_name='study')
    op.drop_table('study')
    op.drop_index(op.f('ix_healthinsurance_telephone'), table_name='healthinsurance')
    op.drop_index(op.f('ix_healthinsurance_name'), table_name='healthinsurance')
    op.drop_index(op.f('ix_healthinsurance_id'), table_name='healthinsurance')
    op.drop_index(op.f('ix_healthinsurance_email'), table_name='healthinsurance')
    op.drop_table('healthinsurance')
    # ### end Alembic commands ###
