"""empty message

Revision ID: b08199a10c3b
Revises: 12fd05b3f483
Create Date: 2021-10-31 21:17:39.637795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08199a10c3b'
down_revision = '12fd05b3f483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('typestudy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_typestudy_id'), 'typestudy', ['id'], unique=False)
    op.add_column('study', sa.Column('type_study_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'study', 'typestudy', ['type_study_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study', type_='foreignkey')
    op.drop_column('study', 'type_study_id')
    op.drop_index(op.f('ix_typestudy_id'), table_name='typestudy')
    op.drop_table('typestudy')
    # ### end Alembic commands ###
