"""arreglos en user y study

Revision ID: ce59dcd6f7e9
Revises: 8010c7229f8f
Create Date: 2021-10-28 03:38:28.600124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce59dcd6f7e9'
down_revision = '8010c7229f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('healthinsurance', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('healthinsurance', 'telephone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'licence',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'dni',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('user', 'dni',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'licence',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('healthinsurance', 'telephone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthinsurance', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
