"""empty message

Revision ID: e87efa504ad6
Revises: 267922b2ec8e
Create Date: 2021-11-08 00:24:18.599145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87efa504ad6'
down_revision = '267922b2ec8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samplebatch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samplebatch_id'), 'samplebatch', ['id'], unique=False)
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_appointment', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_id'), 'appointment', ['id'], unique=False)
    op.add_column('sample', sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('sample', sa.Column('picked_up_by', sa.String(), nullable=True))
    op.add_column('sample', sa.Column('picked_up_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sample', sa.Column('sample_batch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sample', 'samplebatch', ['sample_batch_id'], ['id'])
    op.drop_column('sample', 'retired_by')
    op.add_column('study', sa.Column('payment_receipt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'payment_receipt')
    op.add_column('sample', sa.Column('retired_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_column('sample', 'sample_batch_id')
    op.drop_column('sample', 'picked_up_date')
    op.drop_column('sample', 'picked_up_by')
    op.drop_column('sample', 'created_date')
    op.drop_index(op.f('ix_appointment_id'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_samplebatch_id'), table_name='samplebatch')
    op.drop_table('samplebatch')
    # ### end Alembic commands ###
