"""empty message

Revision ID: f13503ed6e95
Revises: 04b3279fb7e3
Create Date: 2021-11-15 02:59:46.786430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f13503ed6e95'
down_revision = '04b3279fb7e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('delayed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'delayed')
    # ### end Alembic commands ###
